### ISSUE TITLE
About bandwidth of bidirectional copy

### ISSUE THREAD

**Issue by Fanoid** [NVIDIA/nvbandwidth#11]
I am using this tool to test the bandwidth of PCIe with A100 GPU.

When performing unidirectional copies, the results for `host_to_device_memcpy_ce` and `device_to_host_memcpy_ce` are as expected, around 25-26GB/s. However, when performing bidirectional copies, the result for `device_to_host_bidirectional_memcpy_ce` is still relatively normal, around 24GB/s, while the result for `host_to_device_bidirectional_memcpy_ce` is much slower, only 12-13GB/s.

Because I couldn't find similar test results online, it is difficult for me to determine the reasonableness of these results. So I would like to ask if anyone has experienced similar performance degradation during bidirectional copies.

Additionally, if multiple GPUs are copying simultaneously, the performance further decreases. For example, the bandwidth measured by `host_to_all_bidirectional_memcpy_ce` is only about 5-6GB/s.

Furthermore, upon examining the source code, I found a small trick used during bidirectional copy testing: [link](https://github.com/NVIDIA/nvbandwidth/blob/6cefdda0b5dec0b75c3df90bf5c36fc7d250acd6/testcases_ce.cpp#L58C13-L58C13). The amount of data copied from device to host (DtoH) is intentionally set to twice the amount of data copied from host to device (HtoD) in order to interfere correctly. This "2" coefficient coincidentally matches the ratio of DtoH to HtoD bandwidth that we tested, allowing DtoH and HtoD copies to finish almost simultaneously. The simultaneous completion of both copies is closely related to the correctness of the test results.

Therefore, I speculate if the you guys @fiserwy @ramasubramanianrahul also obtained the DtoH to HtoD bandwidth ratio as 2:1, which is why they specifically set the amount of data copied from DtoH to be twice as much.
Would you please give some explanation about this setting? I would very appreciated if you can help me about my issue.

**Comment by deepakcu** [comment]
Results of bidirectional copy may depend on the system configuration. What CPU do you use?
In the mult-gpu scenario, measured bandwidth can vary depending on the interconnection topology as well (for e.g. how GPUs are attached to the root-complex via PCIe switches). Note that nvbandwidth is a tool that reports bandwidth numbers on the given system configuration.

For bidirectional copies, the interference stream is intentionally set to copy twice the data on the measured stream to ensure (close to perfect) traffic overlap between the streams during measurement. Hope that clarifies.

**Comment by Fanoid** [comment]
Hi @deepakcu thanks for your kindly response. The CPU is Intel Icelake 8369B or 8368B (tested on two machines).

Regarding the issue of data size of bidirectional copies, I realized that I misunderstood a fact earlier: I thought that in all bidirectional tests, the copy size of DtoH was set to twice that of HtoD, but in fact, it is always the copy size of the interference stream that is set to twice that of the measured stream. Thank you for your clarification. 

So now my only issue is why the HtoD transfer is so slow during bidirectional copying. I will continue to investigate the cause.
