### ISSUE TITLE
Published Releases

### ISSUE THREAD

**Issue by rafsalas19** [NVIDIA/nvbandwidth#12]
Hello,
I am part of Azure AI/HPC Engineering and would like to include this tool into our Azure AI/HPC marketplace image that we provide our customers to use on Azure ND/NC VM offerings. We had been using CUDA samples and some internal solutions to get BW results. However, this seems better suited for the task.

I was wondering if you could publish a release of this project. We like to control our dependencies with versioning.

Please let me know if you would be receptive to that or if you have any questions about our use case?

-Rafael Salas

**Comment by deepakcu** [comment]
Sounds good. We'll have this ready soon.

**Comment by rafsalas19** [comment]
Awesome!

**Comment by deepakcu** [comment]
@rafsalas19 tags have been created here - https://github.com/NVIDIA/nvbandwidth/tags
