### ISSUE TITLE
loop index unused

### ISSUE THREAD

**Issue by ImanHosseini** [NVIDIA/nvbandwidth#8]
https://github.com/NVIDIA/nvbandwidth/blob/67daa2d2b28c13a41db79ffd035dd9d96f66a0fd/kernels.cu#L21
Is this correct? The loop index, `i` is not used anywhere in the loop body. Shouldn't the offset be updated based on `i`?
I thought this is supposed to control how many elements each thread copies.

**Comment by ramasubramanianrahul** [comment]
Hi.. thank you for raising this issue.
This is in fact correct. We time the copy of loopCount * bufferSize bytes for out bandwidth calculation. Please take a  look at the code in memcpy.cpp:306 for the exact calculation.

Thanks
HTH
